### ISSUE TITLE
Неверное списание средств при оплате с карты.

### ISSUE THREAD

**Issue by Gameunkulus** [Gameunkulus/javaqa-team-diplom-Oskina-Bugrov#2]
# Описание.
Вместо списывания суммы покупки с баланса на карте функция присваивает балансу значение потраченной суммы.
https://github.com/Gameunkulus/javaqa-team-diplom-Oskina-Bugrov/blob/a61475cce656f2a4e15bccde799ab0cd474c4678/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L44-L47

# Шаги воспроизведения.
1. Открыть
2. Создать тест на проверку функции pay в тестовой программе. 
3. Создать новую переменную CreditAccount account = new CreditAccount с соблюдением условий переменных и положительным балансом (3000).
4. Ввести команду account.pay(50).
5. Запустить программу
6. Посмотреть на вывод в консоли

Ожидаемый результат: Вывод сообщения о сумме  на счете 2950.
Фактический результат: Вывод сообщения о сумме  на счете -50.

# Окружение.
* Операционная система: Windows 10 Домашняя для одного языка 21H2
* IDE: IntelliJ IDEA 2021.3 (Community Edition)
* Java: OpenJDK 11

**Comment by Margarita2113** [comment]
исправлено

**Comment by Margarita2113** [comment]
исправлено
